# Generated by Django 3.2 on 2025-05-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('téléphone', models.CharField(max_length=20)),
                ('date_creation', models.DateField()),
                ('validate', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Supériere', 'Supériere')], max_length=50)),
                ('type', models.CharField(choices=[('Publique', 'Publique'), ('Privée', 'Privée')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisation', models.BinaryField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField()),
                ('autorisation', models.BinaryField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.localisation'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
        ),
    ]
