# Generated by Django 5.2.1 on 2025-06-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etablissement_autorisation_fichier_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur'),
        ),
    ]
