# Generated by Django 5.2.1 on 2025-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_utilisateur_mot_de_passe_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='type',
            field=models.CharField(choices=[('publique', 'Publique'), ('privée', 'Privée')], default='publique', max_length=20),
        ),
    ]
